### ISSUE TITLE
How to change the input and output bucket?

### ISSUE THREAD

**Issue by mxc19912008** [qianl15/this#24]
Hi, I have a question about how to change the input and output bucket. If I use the docker file(set the dockerizePip: true), then the input and output buckets are set already. If I do not use the docker file and change the input and output bucket in the lambda function, then there will be an error like this:

```
START RequestId: 4650ae51-f18f-11e8-83bd-5b31ee349eb5 Version: $LATEST
Unable to import module 'lambda': 
Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
If you're working with a numpy git repo, try `git clean -xdf` (removes all
files not under version control).  Otherwise reinstall numpy.

Original error was: /var/task/numpy/core/multiarray.so: invalid ELF header
```

Currently I am using `serverless deploy` for the folder `fused-decode-mxnet-lambda`. Any hint is appreciated!

**Comment by qianl15** [comment]
Hi, according to the error log, it seems that the numpy was failed to build. I think you should still set the dockerizePip to `true` to correctly build numpy and other dependencies.

You would be able to specify the intput and output bucket in the payload when invoking lambdas. For example, [end2end_fuse.py#L208-L219](https://github.com/qianl15/this/blob/4d3d5e8041eacc59887dcff1d601d8b344e28c5c/end_to_end/end2end_fuse.py#L208-L219) shows how to do that.

Let me know if you have any other questions!

**Comment by mxc19912008** [comment]
Thank you so much for your reply! I have some problem installing` scannerpy` when running `end2end_fuse.py`, but I'll try to figure it out!

**Comment by qianl15** [comment]
Sure :) I found Scanner has restructured, so please refer to the older version of the [installation guide](https://github.com/qianl15/scanner/tree/61ce0d35e49c92cab265b746bd55ae75ab57fb42#install).
