### ISSUE TITLE
What should be stored in the s3 input bucket?

### ISSUE THREAD

**Issue by mxc19912008** [qianl15/this#25]
Hi, 

Having another problem lol. I was able to change the input and output bucket now, but it seems that there should be more than just a video file in the input bucket. Also the code here indicates that there would be some `protoFile` and `binFile`. Would you mind give some guide regarding what these files are? 
Line 106 to line 118 in `this/lambdas/fused-decode-mxnet-lambda/lambda.py`
```
  protoFileName = 'decode_args{:d}.proto'.format(startFrame)
  binFileName = 'start_frame{:d}.bin'.format(startFrame)
  print('Downloading files {:s} and {:s} for batch {:d} \
        from s3: {:s}/{:s}'.format(protoFileName, binFileName, startFrame, 
          bucketName, inputPrefix))
  s3 = boto3.resource('s3')
  s3ProtoName = inputPrefix + '/' + protoFileName
  s3BinName = inputPrefix + '/' + binFileName
  protoPath = LOCAL_INPUT_DIR + '/' + protoFileName
  binPath = LOCAL_INPUT_DIR + '/' + binFileName
  
  download_s3(s3ProtoName, protoPath)
  download_s3(s3BinName, binPath)
```

Thank you again!

**Comment by qianl15** [comment]
Hi,

They are pairs of intermediate data for video chunks.

When you input a single video file, the code first cuts the video into smaller chunks that are stored as `.proto` and `.bin` files and uploads them to S3. Then each lambda would only need to download and handle one of the chunks (a pair of `.proto` and `.bin` files).

For each pair, `.proto` defines the structure/metadata of this video chunk and `.bin` stores actual data.

Regards.

**Comment by mxc19912008** [comment]
Alright, thanks again for the detailed explanation!
