### ISSUE TITLE
Decoder Link AccessDenied

### ISSUE THREAD

**Issue by mxc19912008** [qianl15/this#26]
Hi,

It seems that the link(https://s3-us-west-2.amazonaws.com/mxnet-params/DecoderAutomataCmd-static) to your decoder does not allow access anymore. When I click it, it shows:
This XML file does not appear to have any style information associated with it. The document tree is shown below. Could you provide a new link or give us access? Thank you so much!
```
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>0639386F77E9D51E</RequestId>
<HostId>
DlR6Hi7YMGJIOpf3Z6zGbw8IY97ks6FHJ4SpKPFF9Svs3WD1fy3H0t3bZv8ZNetAUP1jxiktQQk=
</HostId>
</Error>
```

**Comment by qianl15** [comment]
Hi,

Yes, the binary is expired and I suggest that you follow the instruction [here](https://github.com/qianl15/this#build-decoder) to build your own static decoder. Sorry for the inconvenience! 

It expires every 30 days so we decided to take it down.

Thanks
