### ISSUE TITLE
Error when building Decoder

### ISSUE THREAD

**Issue by mxc19912008** [qianl15/this#27]
Hi,
Sorry that I got another issue: when I execute `make` step specified in the steps to build decoder, an error shows that  'scanner/video/decoder_automata.h'  is not found. Do you have idea about where to find the files specified in the `/this/src/decode-scanner/decoder_automata_cmd.cpp` file?

Thank you again!
Best
```
[ 50%] Building CXX object CMakeFiles/DecoderAutomataCmd.dir/decoder_automata_cmd.cpp.o
/Users/xma/dev/this/src/decode-scanner/decoder_automata_cmd.cpp:8:10: fatal error:
      'scanner/video/decoder_automata.h' file not found
#include "scanner/video/decoder_automata.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [CMakeFiles/DecoderAutomataCmd.dir/decoder_automata_cmd.cpp.o] Error 1
make[1]: *** [CMakeFiles/DecoderAutomataCmd.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by qianl15** [comment]
Hi,

You need to follow the [installation guide](https://github.com/qianl15/this#install) and install `scanner` under `/opt` directory. The file `scanner/video/decoder_automata.h` should be at `/opt/scanner/scanner/video/decoder_automata.h`.

A link to the specific `decoder_automata.h` file is [here](https://github.com/qianl15/scanner/blob/master/scanner/video/decoder_automata.h).

Thanks

**Comment by mxc19912008** [comment]
Thank you again!!
