### ISSUE TITLE
Is it possible to get your decoder file? Since the scanner project git link failed.

### ISSUE THREAD

**Issue by mxc19912008** [qianl15/this#28]
Hi,

Is it possible to get your decoder file(You mentioned earlier that you need to update your link to your decoder file every month.)? Since when I tried to build my decoder file, the scanner project git link(wget http://raw.githubusercontent.com/scanner-research/scanner/master/docker-compose.yml) in [here](https://github.com/qianl15/scanner/tree/61ce0d35e49c92cab265b746bd55ae75ab57fb42#install) failed.

I am in a hurry to finish a course project and it is near the end of the semester, it would be really nice if you can send me the decoder file. (My email is xiaochunma.pku@gmail.com)

Thanks again!

**Comment by qianl15** [comment]
I just re-compiled and temporarily uploaded the static binary to [this address](https://s3-us-west-2.amazonaws.com/this-tmp/DecoderAutomataCmd-static). Please download it and let me know when you're finished. It takes 200MB space to store so I'd like to delete it as soon as possible. This binary is going to expire after 31 days.

Also, as for your question, you need to follow the instruction for [Building from source](https://github.com/scanner-research/scanner/wiki/Building-Scanner-from-Source), not the docker one. I should have made it clear.

**Comment by mxc19912008** [comment]
OMG, thank you so much! I downloaded it!
