### ISSUE TITLE
No matching function for call to  "DecoderAutomata"

### ISSUE THREAD

**Issue by jananiej** [qianl15/this#32]
I built and installed the scanner in CPU. I followed your steps. When run make for decode scanner I've got the following error. 
```
/app/src/decode-scanner/decoder_automata_cmd.cpp:61:75: error: no matching function for call to ‘scanner::internal::DecoderAutomata::DecoderAutomata(scanner::DeviceHandle&, int, scanner::internal::VideoDecoderType&)’
     DecoderAutomata* decoder = new DecoderAutomata(device, 1, decoder_type);
                                                                           ^
In file included from /app/src/decode-scanner/decoder_automata_cmd.cpp:8:0:
/opt/scanner/scanner/video/decoder_automata.h:32:3: note: candidate: scanner::internal::DecoderAutomata::DecoderAutomata(scanner::DeviceHandle, scanner::i32, scanner::internal::VideoDecoderType, scanner::internal::VideoDecoder*)
   DecoderAutomata(DeviceHandle device_handle, i32 num_devices,
   ^
/opt/scanner/scanner/video/decoder_automata.h:32:3: note:   candidate expects 4 arguments, 3 provided
```
Is there any problem with number of arguments or did I miss anything?
Thank you

**Comment by qianl15** [comment]
Which version of Scanner did you install? I think you may need to install the modified version of scanner here (as written in the instruction): https://github.com/qianl15/scanner

(Btw, this repo is currently not maintained and some code may be broken. Sorry about that. )

**Comment by jananiej** [comment]
Thank you for the response. Yes I installed your modified version of the scanner. As it is not working, is it possible to get the static binary files for the two models.

**Comment by qianl15** [comment]
Sorry to know that it is not working now; but this is an outdated repo as I do not have time to maintain it. I will mark this repo as archived.

For the latest work on serverless, I recommend this tool: https://github.com/StanfordSNR/gg
Especially, they have an example for [serverless video analytics](https://github.com/StanfordSNR/gg/blob/master/tools/python_sdk/README.md#video-decoding--image-recognition).

Thanks.
